### ISSUE TITLE
Where is book.tex

### ISSUE THREAD

**Issue by Gatsby23** [dendibakh/perf-book#1]
Sorry to trobule you, but where is the book.tex
![image](https://user-images.githubusercontent.com/18000675/145676877-d3178657-fee6-4a04-be16-b058d61052ad.png)

**Comment by josephedwardchang** [comment]
Hi, you need to go into the extracted code folder named: perf-book-main
all the *.tex files are there

**Comment by Gatsby23** [comment]
Sorry, but my pandoc-crossref always told me it's wrong with the pandoc-crossref
![1639228719637](https://user-images.githubusercontent.com/18000675/145678072-39b1939a-c5a3-4d63-99f3-3604c4e0e6f0.jpg)

**Comment by josephedwardchang** [comment]
yes same as mine those errors. but it should work out still and create the pdf book :) at the least you got it running. so, as stated in requirements go [here](https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.6.4) and get the linux one (as I guess you're in linux?) extract the pandoc-crossref* files somewhere and copy it over to the folder:

   `/usr/local/bin`

using the command (i'm quite certain you're a linux beginner?)

   `sudo cp dir-to/Pandoc-crossref* /usr/local/bin`

replace "dir-to" to wherever you extracted the pandoc-crossref* files. as you can see: the usr/local/bin folder contains the pandoc-fignos file that must also contain the pandoc-crossref* files (there are 2 of them)

**Comment by Gatsby23** [comment]
> yes same as mine those errors. but it should work out still and create the pdf book :) at the least you got it running. so, as stated in requirements go [here](https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.6.4) and get the linux one (as I guess you're in linux?) extract the pandoc-crossref* files somewhere and copy it over to the folder:
> 
> `/usr/local/bin`
> 
> using the command (i'm quite certain you're a linux beginner?)
> 
> `sudo cp dir-to/pandoc-crossref* /usr/local/bin`
> 
> replace "dir-to" to wherever you extracted the pandoc-crossref* files. as you can see: the usr/local/bin folder contains the pandoc-fignos file that must also contain the pandoc-crossref* files (there are 2 of them)
> 
> i'm using the commandlines :) sorry, it's much easier if you use the GUI

Finally, I use the Windows.But thank you very much.
