### ISSUE TITLE
Incorrect variable name in `Listing 27 Memory Prefetching: using built-in prefetch hints`

### ISSUE THREAD

**Issue by Snowapril** [dendibakh/perf-book#11]
First of all, thanks for making this great book! 
During keep forwarding with your book, I found some typo(?) which may lead to misunderstanding about `__builtin__prefetch` work (such as "what is that variable a? where it comes from?")
![image](https://user-images.githubusercontent.com/24654975/156910797-16787bb8-a857-41c3-bdc0-b712fcfd5628.png)

This line should be like this 
```c
..
__builtin_prefetch(arr + j, 0, 1); // well before the load
..
```

Thanks. Dear @dendibakh

**Comment by dendibakh** [comment]
Yeah, you're right. Thanks for reporting it!

**Comment by dendibakh** [comment]
Fixed
