### ISSUE TITLE
Incorrect the code line number on page 96

### ISSUE THREAD

**Issue by ujos** [dendibakh/perf-book#8]
Looks like on page 96 there is a typo. The text there references to dependency introduced inside the loop. The loop starts at line 5, really. But the dependency is on the line 6.

![image](https://user-images.githubusercontent.com/70940/146545874-05075d72-086a-4c02-8b0f-5fa71945254b.png)

**Comment by dendibakh** [comment]
@ujos Thanks for all the issues you've opened. I will keep them for now and probably won't address them immediately.
Formatting is hard. Or maybe I'm just bad at LaTex. :) 
Anyway, I will focus on formatting after major changes to the book are in place. Again, thanks for reporting them!

**Comment by ujos** [comment]
Actually this ticket is not about formatting. I believe 5 should be changed with 6 (highlighted)

**Comment by dendibakh** [comment]
Ah, OK. But actually, the loop is on line 5. I was trying to be consistent with the compiler optimization reports. They attribute all transformations inside a loop to the line with its header.

**Comment by ujos** [comment]
I mean that in the book you mentioned some dependency in the loop-body and instead of pointing on the line where dependency is introduced, it refers the ‘for’ statement which confuses the reader. Well… at least me as a reader was confused :)

Best regards
Dima
________________________________

**Comment by dendibakh** [comment]
Ok, I think you're right. Fixed with https://github.com/dendibakh/perf-book/commit/c60aa4d6ab1f0482829d76a481b632c1e6429600. Thanks.
