### ISSUE TITLE
typo in chapter 5.7

### ISSUE THREAD

**Issue by 0x975** [dendibakh/perf-book#80]
Hi @dendibakh, first of all, thank you a lot for bringing your expirience to the public, it's a great piece of knowledge you put into this book!

I was reading up on chapter 5.7 Compiler Optimization Reports (page 71 of pdf version) and it seems like there is a typo here (in bold):

The compiler often decides whether a certain transformation will be beneficial based on its cost model analysis. But it doesn’t always make the optimal choice, **which we can be tuned further.**

**Comment by dendibakh** [comment]
Completely missed it. I will check. Thanks for reporting!

**Comment by dendibakh** [comment]
It was fixed in the final version of the book
